const BRANCH_REDIS_KEY = "MOBILE_CHAT_ND_BRANCH";
const CUSTOMER_ID_REDIS_KEY = "MOBILE_CHAT_ND_CUSTOMER_ID";
const SOCKET_ONLINE_REDIS_KEY = "MOBILE_CHAT_ND_SOCKET_CONNECTED";
const OTP_REDIS_KEY = "otp:";

module.exports = {
  BRANCH_REDIS_KEY,
  CUSTOMER_ID_REDIS_KEY,
  SOCKET_ONLINE_REDIS_KEY,
  OTP_REDIS_KEY,
};
